name = "Davenport-Schinzel_Sequences"
version = "0.1.0"
description = "Formalisation of Davenport-Schinzel sequences and their bounds"
authors = ["Antoine du Fresne von Hohenesche"]
license = "Apache-2.0"
keywords = ["math", "combinatorics", "davenport-schinzel", "sequences"]
defaultTargets = ["Project"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Project"
